spring:
  application:
    name: spring-boot-example
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: cxps@123
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true